version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    networks:
      - backend

  ai_service:
    build: ./ai_service
    volumes:
      - data_volume:/data
      - ./ai_service/model:/model
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - prometheus

  db:
    image: postgres
    environment:
      POSTGRES_DB: logs
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  grafana_data:
  db_data:
  data_volume:
